version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: chatq-postgres
    environment:
      POSTGRES_DB: chatq_assist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: taxcRH51#
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgvector_data:
    driver: local